### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by MrJellyB** [linclark/demo-workshopper#3]
Hey, I was trying to run `workshopper-demo verify sol.js`, but it gave me this error:

> ✗ Error connecting to http://localhost:52078: ECONNREFUSED
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:52078
>     at Object.exports._errnoException (util.js:890:11)
>     at exports._exceptionWithHostPort (util.js:913:20)
>     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1059:14)

my code is:

> `var http = require('http');
> 
> http.createServer(function (req, res) {
>   res.writeHead(200);
>   res.write("Aalan Tzuker☺");
>   res.end();
> }).listen(8081, function () {
>   console.log('Listenning on port 8081...');
> })`

and my exercise.js is:
`const Exercise = require('workshopper-exercise'); module.exports = new Exercise()`

I also tried it with your test exercise and got the same result.

**Comment by david-j-davis** [comment]
I have the same issue, it doesn't matter what I exercise I create, the only exercise that works for me is the test_exercise. I consistantly get the ECONNREFUSED error when I try to verify a solution to the exercise.
